[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = ["production"]

    [plugins.inputs.minifierOptions]
      removeAttributeQuotes = false
      collapseWhitespace    = true
      removeComments        = true
      minifyCSS             = true
      minifyJS              = true
