[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = ["production"]

    [plugins.inputs.minifierOptions]
      removeAttributeQuotes     = false
      collapseWhitespace        = true
      removeComments            = true
      minifyCSS                 = true
      minifyJS                  = true
      sortAttributes            = false
      sortClassName             = false
      removeRedundantAttributes = false
      preventAttributesEscaping = true

[build.processing.html]
  pretty_urls = false
